# -*- coding: utf-8 -*-
"""Работа с Apache Spark

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CpTCEQKj-CJOmhszygfBMTqFlh6wmOik

**Задание**

В файле movies.csv лежит база фильмов. Название фильма записано во втором столбце title.
Разбейте названия фильмов на отдельные слова и посчитайте какое слово встречается чаще всего.  
*Вместо title - Film.*

Если у вас не получится со Спарком, то сделайте задание просто на питоне.  
___________________________________________________________________  

**Выполнила задание**  


*   и со спарком. В качестве результата скрины из среды docker.desctop;
*   и на пайтон.
"""

from google.colab import drive
drive.mount('/content/drive')

from PIL import Image

img_path = '/content/drive/MyDrive/запуск_apache_spark.jpg'
img = Image.open(img_path)
display(img)

img_path = '/content/drive/MyDrive/результат_дз_movies.jpg'
img = Image.open(img_path)
display(img)

# docker run -it --rm --network container:spark-master apache/spark:3.5.0 /opt/spark/bin/pyspark --master spark://spark-master:7077
# lower() — в нижний регистр.
# trim() — удаляем крайние пробелы.
# split(..., ' ') — разделяем название на слова по пробелам.
# explode() — список в строки.
# groupBy('word').count() — подсчитаем повторения.

# >>> from pyspark.sql.functions import explode, split, col, lower, trim
# >>> words = df.select(explode(split(lower(trim(col('Film'))), ' ')).alias('word'))
# >>> word_counts = words.groupBy('word').count().orderBy('count', ascending=False)
# >>> word_counts.show(5)

#импортируем пандас
#выводим таблицу, определяем столбец, с которым работать (Film)
import pandas as pd
film = pd.read_csv('/content/drive/MyDrive/movies.csv', sep = ',', encoding='utf-8')
film.head()

#выводим только нужный столбец
film = pd.read_csv('/content/drive/MyDrive/movies.csv', sep = ',', encoding='utf-8', usecols = ['Film'])
film.head()

#импортируем модуль стринг для отчистки текста от пунктуации
import string

film['Film'] = film['Film'].str.translate(str.maketrans(' ', ' ', string.punctuation))
film.head()

#приводим текст в нижний регистр
film['Film'] = film['Film'].str.lower()
film.head()

#разбиваем на слова
film['Film'] = film['Film'].str.split(' ')
film = film.explode('Film')
film.head()

#производим группировку и
#подсчет вхождений в каждую группу,
#сортируем по убыванию и
#выводит первую строку с максимальным результатом, встретлось чаще всего слово the
film = film.groupby('Film').size().sort_values(ascending=False)
film.head(1)

